# Generated by Django 3.2.9 on 2021-11-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='descripition',
            new_name='description',
        ),
    ]
